#!/usr/bin/env bash
# Bash script that Install nginx on your web-01 server and requirements
sudo apt-get update -y
sudo apt-get install curl -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
if pgrep nginx > /dev/null; then
    killall nginx
fi
nginx
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
nginx -s reload
curl -sI 127.0.0.1 | grep "200 OK"
service nginx start
