#!/usr/bin/env bash
# This script is configureing Nginx server so /redirect_me will redirect to another page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.html
new_webpage="https://www.youtube.com/watch?v=QH2-TGUlwu4"
file="/etc/nginx/sites-available/default"
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me $new_webpage permanent;" $file
sudo service nginx restart
