#!/usr/bin/env bash
# installing load balancer
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*

echo "ENABLED=1" >> /etc/default/haproxy

echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 406166-web-01 34.207.188.239:80 check
    server 406166-web-02 54.174.238.110:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
