#!/usr/bin/env bash
#bash script process and PID life
sudo bash -c "echo $$ > /var/run/myscript.pid"
remove() {
	sudo rm -f /var/run/myscript.pid
	exit
}
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command" && remove' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'remove' SIGQUIT
done
